### PR TITLE
Ui replicaset filtering by role / status

### LINKED ISSUE #667: Add toggle for healthy/unhealthy servers
If 1 of 100 servers is unhealthy it is really hard to find which one it is, and what is wrong with it using just cluster dashboard

### LINKED ISSUE #668: Calculate # of selected servers based on filter
image

`storage` filter changes the number of servers on the dashboard page, so I suggest adding another field to headers for "selected" servers

Current:
```54 total | 0 unhealthy | 86 servers```

Suggest:
```10 selected | 54 total | 0 unhealthy | 86 servers```

### PR DESCRIPTION
**Pull request by iv-ov**
What has been done? Why? What problem is being solved?

I didn't forget about

- [x] Tests
- [x] Changelog
- [x] Documentation (unnecessary)

Close #668
Close #667

### CODE REVIEW

**Comment by iv-ov** [comment]
изображение

- [ ] поехало после ребейза

**Comment by rosik** [comment]
- [x] Long lists look good

image

**Comment by rosik** [comment]
- [ ] scrolling page produces artifacts

image

**Comment by rosik** [comment]
- [ ] Second click on filter button should hide dropdown. Instead it blinks now and remains open.

**Comment by Errora** [comment]
Close https://github.com/tarantool/cartridge/issues/849

**Pull request merged**
